#######################################################################################
# A default configuration that will be loaded for all jupyter books
# See the documentation for help and more options: 
# https://jupyterbook.org/customize/config.html

#######################################################################################
# Book settings
title                       : Network Data Science # The title of the book. Will be placed in the left navbar.
author                      : Benjamin D. Pedigo  # The author of the book
copyright                   : "2022"  # Copyright year to be placed in the footer
logo                        : ./images/logo.png  # A path to the book logo

# Linking
html:
  favicon: ./images/logo.png
  comments:
    hypothesis: true
  use_repository_button: true
  use_issues_button: true
  use_edit_page_button: true
  home_page_in_navbar: true
  google_analytics_id: "G-JYHFQNEPZN"

# Information about where the book exists on the web
repository:
  url: https://github.com/bdpedigo/networks-course
  path_to_book: docs
  branch: main

sphinx:
  config:
    language: en
    html_extra_path: ["slides"]

execute: 
  execute_notebooks: off # TODO turn back on someday

# exclude_patterns: [slides/*]

bibtex_bibfiles:
  - references.bib